version: '3'

services:
  app:
    build: .
    command: .docker/start.sh
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app
    networks:
      - app-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
  db:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: micro_videos
      POSTGRES_PASSWORD: prisma
      POSTGRES_USER: prisma
      POSTGRES_INITDB_ARGS: '--encoding=UTF-8 --lc-collate=C --lc-ctype=C'
    networks:
      - app-network
    # volumes:
    #   - ./init.sql:/docker-entrypoint-initdb.d/init.sql

networks:
  app-network:
    driver: bridge